// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PathfinderDatabaseImplement;

#nullable disable

namespace PathfinderDatabaseImplement.Migrations
{
    [DbContext(typeof(PathfinderDatabase))]
    [Migration("20240128112549_addPathfinder")]
    partial class addPathfinder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PathfinderDatabaseImplement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PathfinderDatabaseImplement.Models.EmployeeSkillLevels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SkillLevelId");

                    b.ToTable("EmployeeSkillLevels");
                });

            modelBuilder.Entity("PathfinderDatabaseImplement.Models.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("PathfinderDatabaseImplement.Models.ProfessionSkillLevels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<int>("SkillLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionId");

                    b.HasIndex("SkillLevelId");

                    b.ToTable("ProfessionSkillLevels");
                });

            modelBuilder.Entity("PathfinderDatabaseImplement.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("PathfinderDatabaseImplement.Models.SkillLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SkillLevels");
                });

            modelBuilder.Entity("PathfinderDatabaseImplement.Models.EmployeeSkillLevels", b =>
                {
                    b.HasOne("PathfinderDatabaseImplement.Models.Employee", "Employee")
                        .WithMany("EmployeeSkillLevels")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PathfinderDatabaseImplement.Models.SkillLevel", "SkillLevel")
                        .WithMany("EmployeeSkillLevels")
                        .HasForeignKey("SkillLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("SkillLevel");
                });

            modelBuilder.Entity("PathfinderDatabaseImplement.Models.ProfessionSkillLevels", b =>
                {
                    b.HasOne("PathfinderDatabaseImplement.Models.Profession", "Profession")
                        .WithMany("ProfessionSkillLevels")
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PathfinderDatabaseImplement.Models.SkillLevel", "SkillLevel")
                        .WithMany("ProfessionSkillLevels")
                        .HasForeignKey("SkillLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profession");

                    b.Navigation("SkillLevel");
                });

            modelBuilder.Entity("PathfinderDatabaseImplement.Models.Employee", b =>
                {
                    b.Navigation("EmployeeSkillLevels");
                });

            modelBuilder.Entity("PathfinderDatabaseImplement.Models.Profession", b =>
                {
                    b.Navigation("ProfessionSkillLevels");
                });

            modelBuilder.Entity("PathfinderDatabaseImplement.Models.SkillLevel", b =>
                {
                    b.Navigation("EmployeeSkillLevels");

                    b.Navigation("ProfessionSkillLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
